version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

    # TODO replace with relevant package ecosystem for your repository
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
