name: Backport
on:
  workflow_dispatch:
    inputs:
      number:
        description: "The pull request # to backport"
        required: true

jobs:
  backport:
    uses: trask/.workflows/.github/workflows/java/backport.yml@main
