name: Build

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # TODO replace with your build

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Build
        run: |
          pip install -e .

  shell-script-check:
    # release branches are excluded to avoid unnecessary maintenance
    if: "!startsWith(github.ref_name, 'release/')"
    uses: ./.github/workflows/reusable-shell-script-check.yml

  markdown-link-check:
    # release branches are excluded to avoid unnecessary maintenance
    if: "!startsWith(github.ref_name, 'release/')"
    uses: ./.github/workflows/reusable-markdown-link-check.yml

  misspell-check:
    # release branches are excluded to avoid unnecessary maintenance
    if: "!startsWith(github.ref_name, 'release/')"
    uses: ./.github/workflows/reusable-misspell-check.yml

  required-status-check:
    # shell-script-check is not required so pull requests are not blocked if new checks are added
    # markdown-link-check is not required so pull requests are not blocked if external links break
    # misspell-check is not required so pull requests are not blocked if new misspellings are added
    needs:
      - build
    if: always()
    runs-on: ubuntu-latest
    steps:
      - if: needs.build.result != 'success'
        run: exit 1
