name: Build

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # TODO replace with your build

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Build
        run: |
          pip install -e .

  markdown-link-check:
    # release branches are excluded to avoid unnecessary maintenance
    if: "!startsWith(github.ref_name, 'release/')"
    uses: trask/.workflows/.github/workflows/markdown-link-check.yml@main
    with:
      config-file: .github/config/markdown-link-check-config.json

  markdown-style-check:
    # release branches are excluded to avoid unnecessary maintenance
    if: "!startsWith(github.ref_name, 'release/')"
    uses: trask/.workflows/.github/workflows/markdown-style-check.yml@main
    with:
      config-file: .github/config/markdown-style-check-config.yml

  misspell-check:
    # release branches are excluded to avoid unnecessary maintenance
    if: "!startsWith(github.ref_name, 'release/')"
    uses: trask/.workflows/.github/workflows/misspell-check.yml@main

  shell-script-check:
    # release branches are excluded to avoid unnecessary maintenance
    if: "!startsWith(github.ref_name, 'release/')"
    uses: trask/.workflows/.github/workflows/shell-script-check.yml@main

  required-status-check:
    # markdown-link-check is not required so pull requests are not blocked if external links break
    needs:
      - build
      - markdown-style-check
      - misspell-check
      - shell-script-check
    if: always()
    runs-on: ubuntu-latest
    steps:
      - if: >
          needs.build.result != 'success' ||
          needs.markdown-style-check.result != 'success' ||
          needs.misspell-check.result != 'success' ||
          needs.shell-script-check.result != 'success'
        run: exit 1
